server:
  port: 12345
spring:
  datasource:
    url: jdbc:mysql://db/rpglifeapp
    username: fontys
    password: fontys
    driver-class-name: com.mysql.jdbc.Driver
    dbcp:
      test-on-borrow: true
      validation-query: SELECT 1
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
